package com.bites.findisland;

public class Main {

    public static void main(String[] args) throws Exception {

        Island island = new Island();
        Dimension dimension = new Dimension(24, 36);
        island.SetSize(dimension);
        island.SetBorder(0, 19);
        island.SetBorder(1, 17);
        island.SetBorder(1, 18);
        island.SetBorder(2, 16);
        island.SetBorder(3, 15);
        island.SetBorder(4, 13);
        island.SetBorder(4, 14);
        island.SetBorder(5, 12);
        island.SetBorder(6, 11);
        island.SetBorder(7, 10);
        island.SetBorder(7, 9);
        island.SetBorder(8, 8);
        island.SetBorder(9, 6);
        island.SetBorder(9, 7);
        island.SetBorder(10, 5);
        island.SetBorder(10, 6);
        island.SetBorder(11, 4);
        island.SetBorder(12, 3);
        island.SetBorder(13, 0);
        island.SetBorder(13, 1);
        island.SetBorder(11, 7);
        island.SetBorder(12, 8);
        island.SetBorder(13, 8);
        island.SetBorder(14, 9);
        island.SetBorder(15, 9);
        island.SetBorder(16, 10);
        island.SetBorder(17, 10);
        island.SetBorder(17, 11);
        island.SetBorder(17, 12);
        island.SetBorder(17, 13);
        island.SetBorder(18, 11);
        island.SetBorder(19, 11);
        island.SetBorder(20, 12);
        island.SetBorder(21, 12);
        island.SetBorder(22, 13);
        island.SetBorder(23, 13);
        island.SetBorder(0, 24);
        island.SetBorder(1, 24);
        island.SetBorder(2, 24);
        island.SetBorder(3, 24);
        island.SetBorder(4, 25);
        island.SetBorder(5, 25);
        island.SetBorder(6, 26);
        island.SetBorder(7, 26);
        island.SetBorder(7, 27);
        island.SetBorder(7, 28);
        island.SetBorder(7, 29);
        island.SetBorder(7, 30);
        island.SetBorder(7, 31);
        island.SetBorder(7, 32);
        island.SetBorder(7, 33);
        island.SetBorder(7, 34);
        island.SetBorder(7, 35);
        island.SetBorder(8, 26);
        island.SetBorder(9, 27);
        island.SetBorder(10, 27);
        island.SetBorder(11, 27);
        island.SetBorder(12, 28);
        island.SetBorder(13, 28);
        island.SetBorder(14, 28);
        island.SetBorder(14, 29);
        island.SetBorder(15, 29);
        island.SetBorder(16, 29);
        island.SetBorder(17, 30);
        island.SetBorder(18, 30);
        island.SetBorder(19, 31);
        island.SetBorder(20, 31);
        island.SetBorder(21, 31);
        island.SetBorder(22, 32);
        island.SetBorder(23, 32);
        island.SetBorder(14, 27);
        island.SetBorder(14, 26);
        island.SetBorder(14, 25);
        island.SetBorder(15, 24);
        island.SetBorder(15, 23);
        island.SetBorder(15, 22);
        island.SetBorder(15, 21);
        island.SetBorder(16, 20);
        island.SetBorder(16, 19);
        island.SetBorder(16, 18);
        island.SetBorder(16, 17);
        island.SetBorder(16, 16);
        island.SetBorder(16, 15);
        island.SetBorder(16, 14);
        island.SetBorder(13, 3);
        island.SetBorder(13, 2);
        island.Show();

        FindIsland findIsland = new FindIsland();
        findIsland.Init(island);
        System.out.println(findIsland.Solve());
    }
}
